/**
 *
 * Clase: MenuPrincipalServidor
 *
 * @version: 0.1
 *
 * @Fecha de creación: 16/05/2020
 *
 * Fecha de Modificación:
 *
 * @author migue 1102838994
 *
 * Copyrigth: CECAR
 *
 */
package edu.cecar.presentacion;

import edu.cecar.componentes.ActializarDatosServidor;
import edu.cecar.componentes.DescargarPDF;
import edu.cecar.servidor.DesplegarServidorHilo;
import java.io.IOException;

public class MenuPrincipalServidor extends javax.swing.JFrame {

    public static final String url
            = "https://drive.google.com/u/0/uc?id="
            + "1F95C1VBAcYCa0yVEPK6NHimg2F1u5Dhb&export=download";

    private DesplegarServidorHilo desplegarServidorHilo;
    
    public static ActializarDatosServidor actializarDatosServidor 
                        = new ActializarDatosServidor();

    /**
     * Creates new form MenuPrincipalServidor
     */
    public MenuPrincipalServidor() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Contenedor = new javax.swing.JPanel();
        jButton1Desplegar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1FlujoEventos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Servidor Deportivo");
        getContentPane().setLayout(null);

        jPanel1Contenedor.setToolTipText("");
        jPanel1Contenedor.setLayout(null);

        jButton1Desplegar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1Desplegar.setText("Desplegar Servidor Deportivo");
        jButton1Desplegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1DesplegarActionPerformed(evt);
            }
        });
        jPanel1Contenedor.add(jButton1Desplegar);
        jButton1Desplegar.setBounds(50, 30, 320, 50);

        jTextArea1FlujoEventos.setEditable(false);
        jTextArea1FlujoEventos.setColumns(20);
        jTextArea1FlujoEventos.setRows(5);
        jTextArea1FlujoEventos.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1FlujoEventos);

        jPanel1Contenedor.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 380, 340);

        getContentPane().add(jPanel1Contenedor);
        jPanel1Contenedor.setBounds(10, 11, 440, 470);

        setSize(new java.awt.Dimension(477, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1DesplegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1DesplegarActionPerformed

        // se descargar el pdf
        DescargarPDF descargarPDF;
        try {
            descargarPDF = new DescargarPDF(url);
            String conexion = descargarPDF.getConexion();

            // Se valida que la conexión, busqueda y descarga del archivo 
            // pdf fue exitosa
            if (conexion.equals("true")) {

                // Se procede a desplegar el servidor
                desplegarServidorHilo
                        = new DesplegarServidorHilo();
                desplegarServidorHilo.start();

            } else {
                // Si existe algún error con respecto a la url 
                System.out.println("Error de descarga");

            }

        } catch (IOException ex) {
            // Si existe algún error con respecto a la url 
            // se informa al cliente
            // Se crea un archivo explicando el error
            System.out.println("Error al descargar el archivo");
            jTextArea1FlujoEventos.append("Error al descargar el archivo");
        }

        jButton1Desplegar.setEnabled(false);

    }//GEN-LAST:event_jButton1DesplegarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Desplegar;
    private javax.swing.JPanel jPanel1Contenedor;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1FlujoEventos;
    // End of variables declaration//GEN-END:variables
}
